# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d917b9f9baeb3182d9dc3bab8046301a91b694eaf56881ed1ec9c55d8f983e6433c14beb7480855fe9f7c2220cc067d76bc9c5d1b3b679c0709a1a727738c5e3

test:
  secret_key_base: 39a49d0b0bcc426890c52a404d6240702f9d0ec0b74f4432ef1d6b0e2039690ca9b09792a6d21916f8d2cc0190ce0c9abafdba4873eaed02c804d7d25952be13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
